server:
  port: 8070
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.1.198:8888
      web-context-unify: false # 默认将调用链路收敛了，会导致链路流控不生效
      datasource:
        flow-rule:   # 这个名字可以随意填写，自定义
          nacos:         # 动态流控规则从nacos加载，在nacos配置中心先配置好
            server-addr: 192.168.1.35:8847
            username: nacos
            password: nacos
            namespace: 4ff20e2f-e020-4cd4-858e-2076ef2400cb
            data-id: sentinel-flow-fule
            data-type: json
            rule-type: flow
